### ISSUE TITLE
preVIEW: COVID-19 search engine 

### ISSUE THREAD

**Issue by LaChirla** [ljl-covid/links#1]
**Thank you** a lot for the links.

zbmed.de maintains a useful search engine on previews:

[preVIEW: COVID-19](https://preview.zbmed.de)

**Comment by ljl-covid** [comment]
Thank you for that one! I had a link to ZBMED but if there's a path from it to that particular service, well, it is not obvious and I haven't found it.

Added to the list via https://github.com/ljl-covid/links/commit/e18f7c04c52f88265a261acd761014b9aeefa036
