### ISSUE TITLE
Additional tracker

### ISSUE THREAD

**Issue by nekineznanec** [ljl-covid/links#2]
Slovenian COVID-19 tracker is missing from the Europe subsection. You can use any of the two below, but the former seems to be more detailed.

1. [https://covid-19.sledilnik.org/en/stats](https://covid-19.sledilnik.org/en/stats)
2. [https://covid19.alpaka.si/en/](https://covid19.alpaka.si/en/)

**Comment by ljl-covid** [comment]
Thanks, added.
